# Generated by Django 3.2 on 2021-05-06 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.UUIDField(default=uuid.uuid4)),
                ('commit_id', models.UUIDField(default=uuid.uuid4)),
                ('flow_metadata', models.JSONField()),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('strategy_id', 'commit_id')},
            },
        ),
    ]
