# Generated by Django 3.2 on 2021-06-07 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("strategy", "0001_store_strategies"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="user",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
