# Generated by Django 3.2 on 2021-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_type", models.CharField(max_length=32)),
                ("block_id", models.IntegerField()),
                ("block_name", models.CharField(max_length=128)),
                ("inputs", models.JSONField()),
                ("validations", models.JSONField()),
                ("output_interface", models.JSONField()),
            ],
            options={
                "unique_together": {("block_type", "block_id")},
            },
        ),
    ]
