# Generated by Django 3.2 on 2021-04-15 13:23

from django.db import migrations


def seed_blocks_into_registry(apps, schema_editor):
    BlockRegistry = apps.get_model("orchestrator", "BlockRegistry")

    BlockRegistry(
        block_type="DATA_BLOCK",
        block_id=1,
        block_name="US Stock Data",
        inputs=[
            {
                "fieldData": {
                    "base": "/equityName?name=",
                    "method": "GET",
                },
                "fieldName": "Equity Name",
                "fieldType": "search",
                "fieldVariableName": "equity_name",
            },
            {
                "fieldData": {"base": "/candlestick", "method": "GET"},
                "fieldName": "Candlesticks",
                "fieldType": "dropdown",
                "fieldVariableName": "candlestick",
            },
            {
                "fieldName": "Date Range",
                "fieldType": "date_range",
                "fieldVariableNames": ["start_date", "end_date"],
            },
        ],
        validations={
            "input": {"required": [], "allowed_blocks": []},
            "output": [{"blockType": "DATA_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["open", "high", "low", "close", "volume"]
        }
    ).save()

    BlockRegistry(
        block_type="DATA_BLOCK",
        block_id=2,
        block_name="Crypto Data",
        inputs=[
            {
                "fieldData": {
                    "base": "/cryptoName?name=",
                    "method": "GET",
                },
                "fieldName": "Crypto Name",
                "fieldType": "search",
                "fieldVariableName": "crypto_name",
            },
            {
                "fieldData": {"base": "/candlestick", "method": "GET"},
                "fieldName": "Candlesticks",
                "fieldType": "dropdown",
                "fieldVariableName": "candlestick",
            },
            {
                "fieldName": "Date Range",
                "fieldType": "date_range",
                "fieldVariableNames": ["start_date", "end_date"],
            },
        ],
        validations={
            "input": {"required": [], "allowed_blocks": []},
            "output": [{"blockType": "DATA_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["open", "high", "low", "close", "volume"]
        }
    ).save()

    BlockRegistry(
        block_type="COMPUTATIONAL_BLOCK",
        block_id=1,
        block_name="Technical Indicators",
        inputs=[
            {
                "fieldData": {
                    "base": "/indicator",
                    "method": "GET",
                    "onChange": "indicatorField?indicatorName=",
                },
                "fieldName": "Indicator Name",
                "fieldType": "dropdown",
                "fieldVariableName": "indicator_name",
            },
        ],
        validations={
            "input": {
                "required": [{"blockType": "DATA_BLOCK", "number": 1}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "DATA_BLOCK"},
                    {"blockId": "2", "blockType": "DATA_BLOCK"},
                ],
            },
            "output": [{"blockType": "COMPUTATIONAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["open", "high", "low", "close", "volume"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=1,
        block_name="Intersect",
        inputs=[
            {
                "fieldData": {"base": "/eventAction", "method": "GET"},
                "fieldName": "Event Action",
                "fieldType": "dropdown",
                "fieldVariableName": "event_action",
            },
        ],
        validations={
            "input": {
                "required": [{"blockType": "COMPUTATIONAL_BLOCK", "number": 2}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "COMPUTATIONAL_BLOCK"}
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=2,
        block_name="Saddle",
        inputs=[
            {
                "fieldData": {"base": "/saddleType", "method": "GET"},
                "fieldName": "Saddle Type",
                "fieldType": "dropdown",
                "fieldVariableName": "saddle_type",
            },
            {
                "fieldData": {"base": "/eventAction", "method": "GET"},
                "fieldName": "Event Action",
                "fieldType": "dropdown",
                "fieldVariableName": "event_action",
            },
            {
                "fieldName": "Consecutive Up",
                "fieldVariableName": "consecutive_up",
                "fieldType": "input",
            },
            {
                "fieldName": "Consecutive Down",
                "fieldVariableName": "consecutive_down",
                "fieldType": "input",
            },
        ],
        validations={
            "input": {
                "required": [{"blockType": "COMPUTATIONAL_BLOCK", "number": 1}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "COMPUTATIONAL_BLOCK"}
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 2}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=3,
        block_name="And",
        inputs=[],
        validations={
            "input": {
                "required": [{"blockType": "SIGNAL_BLOCK", "number": 2}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "2", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "4", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "6", "blockType": "SIGNAL_BLOCK"},
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=4,
        block_name="Crossover",
        inputs=[
            {
                "fieldData": {"base": "/crossoverType", "method": "GET"},
                "fieldName": "Event Type",
                "fieldType": "dropdown",
                "fieldVariableName": "event_type",
            },
            {
                "fieldName": "Event Value",
                "fieldVariableName": "event_value",
                "fieldType": "input",
            },
            {
                "fieldData": {"base": "/eventAction", "method": "GET"},
                "fieldName": "Event Action",
                "fieldType": "dropdown",
                "fieldVariableName": "event_action",
            },
        ],
        validations={
            "input": {
                "required": [{"blockType": "COMPUTATIONAL_BLOCK", "number": 1}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "COMPUTATIONAL_BLOCK"},
                    {"blockId": "1", "blockType": "DATA_BLOCK"},
                    {"blockId": "2", "blockType": "DATA_BLOCK"},
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=5,
        block_name="Or",
        inputs=[],
        validations={
            "input": {
                "required": [{"blockType": "SIGNAL_BLOCK", "number": 2}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "2", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "4", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "6", "blockType": "SIGNAL_BLOCK"},
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="SIGNAL_BLOCK",
        block_id=6,
        block_name="Candle Close",
        inputs=[
            {
                "fieldData": {"base": "/candleCloseType", "method": "GET"},
                "fieldName": "Candle Close Type",
                "fieldType": "dropdown",
                "fieldVariableName": "event_type",
            },
            {
                "fieldData": {"base": "/eventAction", "method": "GET"},
                "fieldName": "Event Action",
                "fieldType": "dropdown",
                "fieldVariableName": "event_action",
            },
        ],
        validations={
            "input": {
                "required": [{"blockType": "DATA_BLOCK", "number": 1}],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "DATA_BLOCK"},
                    {"blockId": "2", "blockType": "DATA_BLOCK"},
                ],
            },
            "output": [{"blockType": "SIGNAL_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["timestamp", "order"]
        }
    ).save()

    BlockRegistry(
        block_type="STRATEGY_BLOCK",
        block_id=1,
        block_name="Simple Backtest",
        inputs=[
            {
                "fieldName": "Commission ($)",
                "fieldVariableName": "commission",
                "fieldType": "input",
            },
            {
                "fieldName": "Start Value ($)",
                "fieldVariableName": "start_value",
                "fieldType": "input",
            },
            {
                "fieldName": "Trade Amount Value ($)",
                "fieldVariableName": "trade_amount_value",
                "fieldType": "input",
            },
        ],
        validations={
            "input": {
                "required": [
                    {"blockType": "DATA_BLOCK", "number": 1},
                    {"blockType": "SIGNAL_BLOCK", "number": 1},
                ],
                "allowed_blocks": [
                    {"blockId": "1", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "2", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "3", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "4", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "5", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "6", "blockType": "SIGNAL_BLOCK"},
                    {"blockId": "1", "blockType": "DATA_BLOCK"},
                    {"blockId": "2", "blockType": "DATA_BLOCK"},
                ],
            },
            "output": [{"blockType": "STRATEGY_BLOCK", "number": 1}],
        },
        output_interface={
            "interface": ["trades", "portVals"]
        }
    ).save()


def reverse_blocks_into_registry(apps, schema_editor):
    BlockRegistry = apps.get_model("orchestrator", "BlockRegistry")
    BlockRegistry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_block_registry"),
    ]

    operations = [
        migrations.RunPython(
            seed_blocks_into_registry, reverse_code=reverse_blocks_into_registry
        )
    ]
